name: Discord Commit Notify

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          REPO="${{ github.repository }}"
          ACTOR="${{ github.actor }}"
          URL="${{ github.event.head_commit.url }}"
          COMMIT_MSG="${{ github.event.head_commit.message }}"

          # Escape quotes in commit message
          ESC_MSG=$(echo "$COMMIT_MSG" | sed 's/"/\\"/g')

          # Create JSON payload safely
          PAYLOAD=$(jq -n --arg msg "Hey @playtesters, @${ACTOR} updated **${REPO}**: \"$ESC_MSG\" [view commit](${URL})" '{content: $msg}')

          # Send to Discord
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$PAYLOAD" \
               $DISCORD_WEBHOOK
