name: Discord Commit Notify

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Read commits from GitHub event payload
          MSG="Hey @playtesters, @AIGsniperYt has pushed updates:\n"

          COMMITS=$(jq -c '.commits[]' $GITHUB_EVENT_PATH)
          for commit in $COMMITS; do
            # Get commit message safely
            CMSG=$(echo $commit | jq -r '.message // "No commit message"')
            # Escape quotes for JSON
            ESC_MSG=$(echo "$CMSG" | sed 's/"/\\"/g')
            URL=$(echo $commit | jq -r '.url')
            MSG="${MSG}- ${ESC_MSG} ([view commit](${URL}))\n"
          done

          # Post to Discord webhook
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$MSG\"}" \
               $DISCORD_WEBHOOK
