name: Discord Commit Notify

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit messages to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Build commit list safely
          MSG="Hey @playtesters, @AIGsniperYt has pushed updates:\n"
          for commit in $(jq -r '.commits[] | @base64' <<< "$GITHUB_EVENT_PATH"); do
            _jq() {
              echo ${commit} | base64 --decode | jq -r ${1}
            }
            CMSG=$(_jq '.message')
            CURL_MSG=$(echo "${CMSG:-No commit message}" | sed 's/"/\\"/g')
            URL=$(_jq '.url')
            MSG="${MSG}- ${CURL_MSG} ([view commit](${URL}))\n"
          done
          # Send to Discord
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$MSG\"}" \
               $DISCORD_WEBHOOK
