name: Discord Commit Notify

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit messages to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Build commit list safely
          MSG="Hey @playtesters, @AIGsniperYt has pushed updates:\n"

          COMMITS=$(jq -c '.commits[]' $GITHUB_EVENT_PATH)
          for commit in $COMMITS; do
            CMSG=$(echo $commit | jq -r '.message // "No commit message"')
            CURL_MSG=$(echo "$CMSG" | sed 's/"/\\"/g')
            URL=$(echo $commit | jq -r '.url')
            MSG="${MSG}- ${CURL_MSG} ([view commit](${URL}))\n"
          done

          # Send to Discord
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$MSG\"}" \
               $DISCORD_WEBHOOK
